import streamlit as st
from models import SessionLocal, Ticket

st.set_page_config(page_title="Gate Validator", layout="centered")

# Deep blue and dark red styling for low light / night-time gate scanning
st.markdown("""
    <style>
    .stApp { background-color: #0b1120; color: #e2e8f0; }
    .stTextInput>div>div>input { background-color: #1e293b; color: white; font-size: 20px; font-weight: bold; text-align: center; }
    .stButton>button { background-color: #7f1d1d; color: white; border: none; height: 60px; font-size: 20px; }
    .stButton>button:hover { background-color: #991b1b; color: white; }
    .valid-ticket { background-color: #065f46; padding: 20px; border-radius: 10px; text-align: center; border: 2px solid #34d399; }
    .fake-ticket { background-color: #7f1d1d; padding: 20px; border-radius: 10px; text-align: center; border: 2px solid #f87171; }
    .used-ticket { background-color: #b45309; padding: 20px; border-radius: 10px; text-align: center; border: 2px solid #fbbf24; }
    </style>
""", unsafe_allow_html=True)

st.title("🛡️ Gate Validator")
st.write("Scan a QR code or manually enter the Ticket ID to verify entry.")

# A form ensures the scanner hardware (which acts like a keyboard) can auto-submit
with st.form("scanner_form", clear_on_submit=True):
    scanned_id = st.text_input("Scan QR Code / Enter Ticket ID", placeholder="Waiting for scanner...")
    submit_scan = st.form_submit_button("Verify Ticket", use_container_width=True)

if submit_scan:
    if not scanned_id.strip():
        st.warning("⚠️ Please scan or enter a Ticket ID.")
    else:
        db = SessionLocal()
        try:
            # Clean the scanned input to prevent hidden whitespace errors
            clean_id = scanned_id.strip()
            
            # 1. Query the database for the exact ID
            ticket = db.query(Ticket).filter(Ticket.ticket_id == clean_id).first()
            
            # 2. Catch Fakes (Not in database at all)
            if not ticket:
                st.markdown(
                    f"""<div class="fake-ticket">
                    <h1 style="color: white; margin: 0;">❌ FAKE TICKET</h1>
                    <p style="color: white; font-size: 18px;">ID: {clean_id}<br>This QR code was not generated by this system.</p>
                    </div>""", 
                    unsafe_allow_html=True
                )
            
            # 3. Catch Duplicates (Already scanned)
            elif ticket.status == "Used":
                st.markdown(
                    f"""<div class="used-ticket">
                    <h1 style="color: white; margin: 0;">⚠️ ALREADY SCANNED</h1>
                    <p style="color: white; font-size: 18px;">This ticket has already been used to enter.</p>
                    </div>""", 
                    unsafe_allow_html=True
                )
                
            # 4. Valid Entry
            elif ticket.status in ["Sold", "With_Vendor"]:
                # Update status to lock it out from future scans
                ticket.status = "Used"
                db.commit()
                
                # Show massive green success message
                st.markdown(
                    f"""<div class="valid-ticket">
                    <h1 style="color: white; margin: 0;">✅ ACCESS GRANTED</h1>
                    <p style="color: white; font-size: 18px;">Type: {ticket.ticket_type}<br>Valid Entry Logged.</p>
                    </div>""", 
                    unsafe_allow_html=True
                )
                
        except Exception as e:
            st.error(f"Database error during verification: {e}")
            db.rollback()
        finally:
            db.close()
